// Re-export from generated types. Do not edit this file manually.
// Regenerate with: npm run db:types
export type { Database, Json, Tables, TablesInsert, TablesUpdate, Enums } from "./database.generated";
