#!/usr/bin/env node
// scripts/setup.mjs
// ---------------------------------------------------------------------------
// One-command local dev bootstrap for Barn Time Portal.
//
// Usage:  node scripts/setup.mjs   (or: npm run setup)
//
// What it does:
//   1. Runs preflight checks (Node, Docker, Supabase CLI, required files)
//   2. Starts local Supabase (idempotent — safe if already running)
//   3. Resets DB (applies migrations + seeds test data)
//   4. Writes .env.local from `supabase status -o env`
//   5. Prints summary with URLs and test accounts
// ---------------------------------------------------------------------------
import { execSync, spawnSync } from "node:child_process";
import { writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { printPreflight, SUPABASE_BIN, ROOT } from "./preflight.mjs";

function run(cmd, label) {
  console.log(`\n${label}...`);
  try {
    execSync(cmd, { stdio: "inherit", cwd: ROOT, timeout: 300_000 });
  } catch (e) {
    console.error(`\nFailed: ${label}`);
    process.exit(1);
  }
}

function runCapture(cmd) {
  const result = spawnSync(cmd, { shell: true, cwd: ROOT, encoding: "utf-8", timeout: 30_000 });
  return result.stdout || "";
}

// ---------------------------------------------------------------------------
// 1. Preflight
// ---------------------------------------------------------------------------
console.log("\n=== Barn Time — Local Dev Setup ===");

const ok = printPreflight({ exitOnFail: true });

// ---------------------------------------------------------------------------
// 2. Start Supabase (idempotent)
// ---------------------------------------------------------------------------
run(`"${SUPABASE_BIN}" start`, "Starting local Supabase (this may take a minute on first run)");

// ---------------------------------------------------------------------------
// 3. Reset DB
// ---------------------------------------------------------------------------
run(`"${SUPABASE_BIN}" db reset`, "Applying migrations and seeding database");

// ---------------------------------------------------------------------------
// 4. Write .env.local from supabase status -o env
// ---------------------------------------------------------------------------
console.log("\nGenerating .env.local...");

const envOutput = runCapture(`"${SUPABASE_BIN}" status -o env`);

// Parse KEY=VALUE lines from `supabase status -o env`
const envMap = {};
for (const line of envOutput.split("\n")) {
  const match = line.match(/^([A-Z_]+)="?([^"]*)"?$/);
  if (match) {
    envMap[match[1]] = match[2];
  }
}

const apiUrl = envMap.API_URL || "http://localhost:54321";
const anonKey = envMap.ANON_KEY || "";
const serviceKey = envMap.SERVICE_ROLE_KEY || "";

if (!anonKey || !serviceKey) {
  console.warn(
    "Warning: Could not parse keys from `supabase status -o env`.\n" +
    "Run `npm run local:status` and copy the values into .env.local manually."
  );
}

const envContent = [
  `# Auto-generated by npm run setup — ${new Date().toISOString()}`,
  `NEXT_PUBLIC_SUPABASE_URL=${apiUrl}`,
  `NEXT_PUBLIC_SUPABASE_ANON_KEY=${anonKey}`,
  `SUPABASE_SERVICE_ROLE_KEY=${serviceKey}`,
  "",
].join("\n");

writeFileSync(resolve(ROOT, ".env.local"), envContent, "utf-8");
console.log("Wrote .env.local");

// ---------------------------------------------------------------------------
// 5. Summary
// ---------------------------------------------------------------------------
const studioUrl = envMap.STUDIO_URL || "http://localhost:54323";
const inbucketUrl = envMap.INBUCKET_URL || "http://localhost:54324";

console.log(`
=== Setup complete ===

  Start the app:    npm run dev
  App:              http://localhost:3000
  Supabase Studio:  ${studioUrl}
  Inbucket (email): ${inbucketUrl}

  Sign in with any test account using magic link:
    admin@barntime.net
    owner@sunsetweddings.com
    coordinator@sunsetweddings.com
    viewer@sunsetweddings.com
    vendor@bayareasound.com
    venuemanager@redwoodestate.com
`);
