#!/usr/bin/env bash
# ------------------------------------------------------------------
# Barn Time Portal — One-command local dev setup
# ------------------------------------------------------------------
# Usage:  ./scripts/setup.sh
#
# What it does:
#   1. Installs npm dependencies
#   2. Starts local Supabase (Docker must be running)
#   3. Resets DB (applies migrations + seeds test data)
#   4. Writes .env.local from live Supabase status output
#   5. Prints next steps
# ------------------------------------------------------------------
set -euo pipefail

cd "$(dirname "$0")/.."

echo ""
echo "=== Barn Time — Local Dev Setup ==="
echo ""

# ---- 1. Install deps ------------------------------------------------
if [ ! -d node_modules ]; then
  echo "Installing dependencies..."
  npm ci
else
  echo "Dependencies already installed."
fi

# ---- 2. Start Supabase ---------------------------------------------
echo ""
echo "Starting local Supabase (this may take a minute on first run)..."
supabase start

# ---- 3. Reset DB (migrations + seed) --------------------------------
echo ""
echo "Applying migrations and seeding database..."
supabase db reset

# ---- 4. Write .env.local from supabase status -----------------------
echo ""
echo "Generating .env.local..."

API_URL=$(supabase status --output json | python3 -c "import sys,json; print(json.load(sys.stdin)['API_URL'])" 2>/dev/null || true)
ANON_KEY=$(supabase status --output json | python3 -c "import sys,json; print(json.load(sys.stdin)['ANON_KEY'])" 2>/dev/null || true)
SERVICE_KEY=$(supabase status --output json | python3 -c "import sys,json; print(json.load(sys.stdin)['SERVICE_ROLE_KEY'])" 2>/dev/null || true)

if [ -z "$API_URL" ] || [ -z "$ANON_KEY" ] || [ -z "$SERVICE_KEY" ]; then
  echo "Warning: could not parse supabase status JSON. Falling back to defaults."
  API_URL="http://localhost:54321"
  ANON_KEY="<run 'supabase status' and copy anon key>"
  SERVICE_KEY="<run 'supabase status' and copy service_role key>"
fi

cat > .env.local <<EOF
# Auto-generated by scripts/setup.sh — $(date -Iseconds)
NEXT_PUBLIC_SUPABASE_URL=${API_URL}
NEXT_PUBLIC_SUPABASE_ANON_KEY=${ANON_KEY}
SUPABASE_SERVICE_ROLE_KEY=${SERVICE_KEY}
EOF

echo "Wrote .env.local"

# ---- 5. Done --------------------------------------------------------
echo ""
echo "=== Setup complete ==="
echo ""
echo "  Start the app:   npm run dev"
echo "  Open:            http://localhost:3000"
echo "  Inbucket (mail): http://localhost:54324"
echo ""
echo "  Sign in with any test account using magic link:"
echo "    admin@barntime.net"
echo "    owner@sunsetweddings.com"
echo "    coordinator@sunsetweddings.com"
echo "    viewer@sunsetweddings.com"
echo "    vendor@bayareasound.com"
echo "    venuemanager@redwoodestate.com"
echo ""
